INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'air');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'bed');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'boy, yob');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'cat, act');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'dog, god');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'fog');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'fun');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'fox');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'hot, tho');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'joy');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'map, amp');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'oil');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'pet');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'sea');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'toy');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'two, tow');
INSERT INTO Words (WordLength, Possibilities) VALUES (3, 'zoo');

INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'also');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'army');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'bird');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'city');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'date');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'easy');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'evil, live, veil, vile');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'farm');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'fish');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'good');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'hero');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'king, gink');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'lord');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'menu');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'rain');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'wild');
INSERT INTO Words (WordLength, Possibilities) VALUES (4, 'wind');

INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'asked');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'berry');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'doves');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'eagle');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'flute');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'goose');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'happy');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'ideal');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'joint');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'kites');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'leafs, false, fleas');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'music');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'notes, onset, stone, tones');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'peach, cheap');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'queen');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'toxic');
INSERT INTO Words (WordLength, Possibilities) VALUES (5, 'water');

INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'agenda');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'border');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'bottle');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'circle, cleric');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'combat');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'damage');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'defend, fended');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'effect');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'empire, premie');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'female');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'father');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'garden, danger, ranged');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'ground');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'hidden');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'income');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'island');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'little');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'master, matres, stream');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'method');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'nobody');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'person');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'relate');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'secure, rescue');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'spirit');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'travel');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'update');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'volume');
INSERT INTO Words (WordLength, Possibilities) VALUES (6, 'winter, twiner');
